import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import random
from selenium.common.exceptions import WebDriverException

#removing the unwanted braces and brackets
from pynput.keyboard import Controller, Key


keyboard = Controller()



def auto_type_rough_code(code,driver):
    """Clears the existing code, types the given code, clicks Run twice, then extracts the solution code."""
    print("🔃 Typing code into editor...")

    # Locate and activate the editor
    editor = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CLASS_NAME, "ace_editor"))
    )
    driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", editor)
    time.sleep(1)

    actions = ActionChains(driver)
    actions.move_to_element(editor).click().perform()
    time.sleep(1)

    # Ensure the editor is active
    if "ace_focus" not in editor.get_attribute("class"):
        print("❌ Editor not focused, retrying...")
        actions.move_to_element(editor).click().perform()
        time.sleep(1)

    # **Clear Existing Code using Ctrl + A & Delete**
    actions.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
    time.sleep(0.2)
    actions.send_keys(Keys.DELETE).perform()
    time.sleep(0.5)

    # **Auto-Type Code One Character at a Time**
    for char in code:
        actions.send_keys(char)
        actions.perform()
        time.sleep(0.03)

    print("🎳 Rough Code typed successfully.")
    

def clicking_run_btn_twice(driver,run_button_id):
    
    # **Click Run Button Twice**
    for i in range(2):  # Click twice
        print(f"🔄 Clicking Run button ({i+1}/2)...")
        try:
            run_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.ID, run_button_id))  # Corrected ID
            )
            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", run_button)
            time.sleep(0.5)
            run_button.click()
            print(f"🚀 Run button clicked successfully ({i+1}/2).")

            # Wait for compilation before second click
            if i == 0:
                print("⏳ Waiting for compilation...")
                time.sleep(5)  # Adjust based on compilation time
        except Exception as e:
            print(f"❌ Failed to click Run button: {e}")
            
def clicking_run_btn_once(driver,run_button_id):
    # **Click Run Button once**
    
        print(f"🔁 Clicking Run button ")
        try:
            run_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.ID, run_button_id))  # Corrected ID
            )
            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", run_button)
            time.sleep(0.2)
            run_button.click()
            print(f"🚀 Run button clicked successfully one time.")
            time.sleep(7)

        except Exception as e:
            print(f"❌ Failed to click Run button one time: {e}")


def select_until_end(driver, repeats=20):
    # Create an ActionChains instance
    actions = ActionChains(driver)

    # Perform the key combination multiple times
    for _ in range(repeats):
        actions.key_down(Keys.CONTROL).key_down(Keys.SHIFT).send_keys(Keys.ARROW_RIGHT).key_up(Keys.SHIFT).key_up(Keys.CONTROL).perform()
        time.sleep(0.05)  # Small delay to avoid overwhelming the system

    # Press DELETE to remove the selected text
    actions.send_keys(Keys.DELETE).perform()

    print("♻️ The auto-created braces and brackets generated by the editor are cleared.")


def auto_type_extracted_code(clean_code,driver):
    # **Auto-Type the Extracted Code**
    try:
        print("📝 Typing extracted code into editor...")

        editor = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CLASS_NAME, "ace_editor"))
        )
        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", editor)
        time.sleep(1)

        actions = ActionChains(driver)
        actions.move_to_element(editor).click().perform()
        time.sleep(1)

        # **Clear Existing Code**
        actions.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        time.sleep(0.2)
        actions.send_keys(Keys.DELETE).perform()
        time.sleep(0.5)

        # **Auto-Type Extracted Code**
        human_typing(driver,clean_code, actions)

        print("✅ Extracted code typed successfully.")
    
    #Exception to handle in typing code in editor
    except WebDriverException as e:
        print(f"❌ Error detected while typing: {e}")
        return


def human_typing(driver,text, actions):
    try:
        text = "\n".join(line.lstrip() for line in text.splitlines())  
        typo_chance = 0.05  # 5% chance of a typo
        backspace_delay = random.uniform(0.15, 0.3)  # Delay before correcting typo

        for char in text:
            if random.random() < typo_chance and char.isalnum():  
                # Introduce a typo by sending a wrong character
                wrong_char = random.choice("abcdefghijklmnopqrstuvwxyz0123456789")
                actions.send_keys(wrong_char)
                actions.perform()
                time.sleep(backspace_delay)  # Simulate thinking time before correction

                # Simulate pressing backspace **only once** to remove the wrong character
                actions.send_keys(Keys.BACKSPACE)
                actions.perform()
                time.sleep(random.uniform(0.1, 0.2))  # Pause before retyping correctly

            # Type the correct character
            actions.send_keys(char)
            actions.perform()

            # Introduce a realistic typing delay
            base_delay = random.uniform(0.05, 0.2)  
            if random.random() < 0.1:  # 10% chance of a longer pause
                base_delay += random.uniform(0.3, 0.7)

            time.sleep(base_delay)

        #Select and remove extra braces after code typed successfully
        select_until_end(driver)
    
    # Exception handling for any interrupt while typing code in the editor
    except WebDriverException as e:
        print(f"❌ Error detected while typing as human typing: {e}")
        return

